name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true      # 🔥 Ensures PaperMod is cloned
          fetch-depth: 0        # 🔄 Full history (needed for submodules)

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.147.2'
          extended: true

      - name: Clean public folder
        run: rm -rf public

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./public

      - name: List output files
        run: ls -la public
